# Generated by Django 3.1 on 2020-10-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_profile_following_+', through='profiles.FollowRequest', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=7),
        ),
    ]
